### ISSUE TITLE
When month is set to width: 'long', title gets cut off if it's too close to the side

### ISSUE THREAD

**Issue by gmacev** [demark-pro/react-booking-calendar#3]
Can't seem to fix this with css no matter what. If I fix one, the other gets even more cut off, and vice versa

<img width="350" alt="image" src="https://user-images.githubusercontent.com/21122921/229896244-dc3a90c9-7220-4eb1-9a03-3f9685b85da5.png">

<img width="363" alt="image" src="https://user-images.githubusercontent.com/21122921/229896508-cc50bc54-788e-4e39-a9a4-d0c7e23376bd.png">

```
dateFnsOptions={{
  weekStartsOn: 1,
  locale: {
    ...dateFnsLocale,
    localize: {
      ...dateFnsLocale.localize!,
      month: (date: Date) => {
        if (!dateFnsLocale?.localize?.month) return '';
        return dateFnsLocale.localize.month(date, { width: 'long' });
      },
    },
  },
}}
```

**Comment by demark-pro** [comment]
Fixed in version 4x
